{% set name = "toolbox_utils" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/toolbox_utils-{{ version }}.tar.gz
  sha256: 5de923f39f2e371f4eeeda76782c79013d4fa5f333a502e8a4c147b71f689072

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.8
    - dateparser
    - tabulate
    - numpy
    - scipy
    - pandas
    - pint-pandas
    - pint
    - pydantic
    - typing-extensions
    - odfpy >=1.4.1
    - xlrd >=2.0.1
    - openpyxl >=3.0.7
    - pyxlsb >=1.0.8
    - pytables >=3.6.1
    - matplotlib-base >=3.3.2
    - xlsxwriter

test:
  imports:
    - toolbox_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/toolbox-utils/
  summary: Python toolbox for common utilities
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
