schema_version: 1

context:
  name: toolbox_utils
  version: "5.7.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 213d53a7e0680c35b3a2bd58b89a015b6f299c46cdc478f726a41d3b904d5634

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - dateparser
    - tabulate
    - numpy
    - scipy
    - pandas
    - pint-pandas
    - pint !=0.21
    - pydantic
    - typing-extensions
    - odfpy >=1.4.1
    - xlrd >=2.0.1
    - openpyxl >=3.0.7
    - pyxlsb >=1.0.8
    - pytables >=3.6.1
    - matplotlib-base >=3.3.2
    - xlsxwriter

tests:
  - python:
      imports:
        - toolbox_utils
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Python toolbox for common utilities
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://pypi.org/project/toolbox-utils/

extra:
  recipe-maintainers:
    - timcera

